'use client';

import { useEffect, useState } from 'react';

// export const metadata = {
//   title: 'Home',
//   description: 'Generated by Next.js',
// };

export default function Page() {
  const [movies, setMovies] = useState([]);
  const [loading, setLoading] = useState(true);

  const getMovies = async () => {
    try {
      setLoading(true);
      const response = await fetch(
        'https://nomad-movies.nomadcoders.workers.dev/movies'
      );

      const json = await response.json();
      setMovies(json);
      setLoading(false);
    } catch (error) {}
  };

  useEffect(() => {
    getMovies();
  }, []);
  return <div>{loading ? 'Loading...' : JSON.stringify(movies)}</div>;
}
